sudo docker load -i ./Docker/recorder.tar
sudo docker load -i ./Docker/analyzer.tar
sudo docker load -i ./Docker/fastapiapp.tar
sudo docker load -i ./Docker/streamer.tar
sudo docker load -i ./Docker/frontend.tar
sudo docker load -i ./Docker/mongo_express.tar
sudo docker load -i ./Docker/minio.tar
sudo docker load -i ./Docker/mongo.tar
sudo docker load -i ./Docker/redis.tar
sudo docker load -i ./Docker/mc.tar
sudo docker load -i ./Docker/ubuntu.tar
