sudo docker load -i recorder.tar
sudo docker load -i analyzer.tar
sudo docker load -i fastapiapp.tar
sudo docker load -i streamer.tar
sudo docker load -i frontend.tar
sudo docker load -i mongo_express.tar
sudo docker load -i minio.tar
sudo docker load -i mongo.tar
sudo docker load -i redis.tar
sudo docker load -i mc.tar
